### ISSUE TITLE
Enums are exported as types, cannot be used

### ISSUE THREAD

**Issue by EcksDy** [OpenAPI-Qraft/openapi-qraft#108] opened 2024-07-12 19:29 UTC
Enums inside `schema.ts` are exported correctly. But then inside of `index.ts` everything is exported as types:
```
export type * from "./schema";
```

This leads to the following error when trying to use the enums:
```
'SomeEnum' cannot be used as a value because it was exported using 'export type'. ts(1362)
```

**Comment by radist2s** [comment] 2024-07-14 12:04
@EcksDy, thank you for the feedback, I'll fix it.

**Comment by radist2s** [comment] 2024-07-15 23:19
@EcksDy, I've just released a new `@openapi-qraft/cli@1.12.1-beta.0`, could you please clarify if this works as intended?

**Comment by EcksDy** [comment] 2024-07-17 07:16
Works as intended 🙏

**Comment by radist2s** [comment] 2024-07-20 16:31
Fixed in [`@openapi-qraft/tanstack-query-react-plugin@1.12.1`](https://github.com/OpenAPI-Qraft/openapi-qraft/releases/tag/%40openapi-qraft%2Ftanstack-query-react-plugin%401.12.1).

**Closed by radist2s** 2024-07-20 16:31 UTC
Labels: bug, good first issue
